---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: minipay
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: minipay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
            - name: GF_SERVER_DOMAIN
              value: "167.99.128.137"
            - name: GF_SERVER_ROOT_URL
              value: "http://167.99.128.137:30300/"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "false"
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 384Mi
              cpu: 400m
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grafana-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: minipay
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
