---
# ConfigMap with the database init script
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: minipay
data:
  init.sql: |
    CREATE DATABASE minipay_auth;
    CREATE DATABASE minipay_users;
    CREATE DATABASE minipay_sessions;
    CREATE DATABASE minipay_issuer;
    CREATE DATABASE minipay_tds;
    CREATE DATABASE minipay_settlement;
    CREATE DATABASE minipay_audit;
    CREATE DATABASE minipay_psd2;

    GRANT ALL PRIVILEGES ON DATABASE minipay_auth TO minipay;
    GRANT ALL PRIVILEGES ON DATABASE minipay_users TO minipay;
    GRANT ALL PRIVILEGES ON DATABASE minipay_sessions TO minipay;
    GRANT ALL PRIVILEGES ON DATABASE minipay_issuer TO minipay;
    GRANT ALL PRIVILEGES ON DATABASE minipay_tds TO minipay;
    GRANT ALL PRIVILEGES ON DATABASE minipay_settlement TO minipay;
    GRANT ALL PRIVILEGES ON DATABASE minipay_audit TO minipay;
    GRANT ALL PRIVILEGES ON DATABASE minipay_psd2 TO minipay;

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: minipay
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_DB
              value: minipay
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "minipay"]
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 768Mi
              cpu: 500m
      volumes:
        - name: init-script
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: minipay
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
