---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fraud-model-pvc
  namespace: minipay
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-svc
  namespace: minipay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-svc
  template:
    metadata:
      labels:
        app: fraud-svc
    spec:
      containers:
        - name: fraud-svc
          image: ghcr.io/arobertm/minipay/fraud-svc:149367767af0f55ac4b6818268407ac4264c1d02
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8090
          env:
            - name: MODEL_DIR
              value: /app/model_store
          readinessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 40
            periodSeconds: 15
          volumeMounts:
            - name: model-store
              mountPath: /app/model_store
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 768Mi
              cpu: 1000m
      volumes:
        - name: model-store
          persistentVolumeClaim:
            claimName: fraud-model-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: fraud-svc
  namespace: minipay
spec:
  selector:
    app: fraud-svc
  ports:
    - port: 8090
      targetPort: 8090
