---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tds-svc
  namespace: minipay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tds-svc
  template:
    metadata:
      labels:
        app: tds-svc
    spec:
      containers:
        - name: tds-svc
          image: ghcr.io/arobertm/minipay/tds-svc:10333c9ba2da00e291bbec15a40d1a5e2a9c5302
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8096
          env:
            - name: SERVER_PORT
              value: "8096"
            - name: TDS_BASE_URL
              value: "http://tds-svc:8096"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms64m -Xmx200m -XX:+UseG1GC -XX:MaxMetaspaceSize=128m"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8096
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8096
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8096
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 300m

---
apiVersion: v1
kind: Service
metadata:
  name: tds-svc
  namespace: minipay
spec:
  selector:
    app: tds-svc
  ports:
    - port: 8096
      targetPort: 8096
