---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: issuer-svc
  namespace: minipay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issuer-svc
  template:
    metadata:
      labels:
        app: issuer-svc
    spec:
      containers:
        - name: issuer-svc
          image: ghcr.io/arobertm/minipay/issuer-svc:6b14e74453820fb24a023db66b71a8da3b4d1b6f
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8087
          env:
            - name: SERVER_PORT
              value: "8087"
            - name: SPRING_MAIN_LAZY_INITIALIZATION
              value: "true"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/minipay_issuer
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms32m -Xmx192m -XX:MaxMetaspaceSize=96m -XX:ReservedCodeCacheSize=24m -XX:TieredStopAtLevel=1"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            failureThreshold: 24
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 0
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 384Mi
              cpu: 400m

---
apiVersion: v1
kind: Service
metadata:
  name: issuer-svc
  namespace: minipay
spec:
  selector:
    app: issuer-svc
  ports:
    - port: 8087
      targetPort: 8087
