---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlement-svc
  namespace: minipay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settlement-svc
  template:
    metadata:
      labels:
        app: settlement-svc
    spec:
      containers:
        - name: settlement-svc
          image: ghcr.io/arobertm/minipay/settlement-svc:908fc4337a3488e097c8969ff6f465a4b42d4fb2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8094
          env:
            - name: SERVER_PORT
              value: "8094"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/minipay
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms64m -Xmx256m -XX:+UseG1GC -XX:MaxMetaspaceSize=128m"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8094
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8094
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8094
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 300m

---
apiVersion: v1
kind: Service
metadata:
  name: settlement-svc
  namespace: minipay
spec:
  selector:
    app: settlement-svc
  ports:
    - port: 8094
      targetPort: 8094
