server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: auth-svc

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/minipay_auth}
    username: ${SPRING_DATASOURCE_USERNAME:minipay}
    password: ${SPRING_DATASOURCE_PASSWORD:minipay_secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  # Virtual Threads (Java 21 — Project Loom)
  threads:
    virtual:
      enabled: true

# HashiCorp Vault
vault:
  uri: ${VAULT_URI:http://localhost:8200}
  token: ${VAULT_TOKEN:minipay-vault-token}

# gRPC server port
grpc:
  server:
    port: 9081

# Actuator / Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# PQC Settings
minipay:
  auth:
    # Algoritm JWT: DILITHIUM3 (post-quantum) sau RS256 (clasic)
    jwt-algorithm: DILITHIUM3
    token-ttl-minutes: 60
    refresh-token-ttl-days: 30

logging:
  level:
    ro.minipay: DEBUG
    org.springframework.security: INFO
