server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: network-svc

  threads:
    virtual:
      enabled: true

services:
  vault-url: ${VAULT_URL:http://vault-svc:8085}
  issuer-url: ${ISSUER_URL:http://issuer-svc:8087}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    "[ro.minipay.network]": DEBUG
