---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc
  namespace: minipay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-svc
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      containers:
        - name: auth-svc
          image: ghcr.io/arobertm/minipay/auth-svc:10333c9ba2da00e291bbec15a40d1a5e2a9c5302
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
            - name: grpc
              containerPort: 9081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: GRPC_PORT
              value: "9081"
            - name: MINIDS_ADDRESS
              value: minids-api:8301
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: 256Mi
              cpu: 150m
            limits:
              memory: 512Mi
              cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: minipay
spec:
  selector:
    app: auth-svc
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: grpc
      port: 9081
      targetPort: 9081
