---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc
  namespace: minipay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-svc
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      containers:
        - name: auth-svc
          image: ghcr.io/arobertm/minipay/auth-svc:ad419202de3deb82156f8b2003799ad0a081f720
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
            - name: grpc
              containerPort: 9081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_MAIN_LAZY_INITIALIZATION
              value: "true"
            - name: GRPC_PORT
              value: "9081"
            - name: MINIDS_ADDRESS
              value: minids-api:8301
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms32m -Xmx160m -XX:MaxMetaspaceSize=96m -XX:ReservedCodeCacheSize=24m -XX:TieredStopAtLevel=1"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            failureThreshold: 24
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              memory: 96Mi
              cpu: 100m
            limits:
              memory: 384Mi
              cpu: 400m

---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: minipay
spec:
  selector:
    app: auth-svc
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: grpc
      port: 9081
      targetPort: 9081
