---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc
  namespace: minipay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      containers:
        - name: user-svc
          image: ghcr.io/arobertm/minipay/user-svc:ed372fc4d2740c055c65f2272a47d5f285411e7c
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8082
            - name: grpc
              containerPort: 9082
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: GRPC_PORT
              value: "9082"
            - name: MINIDS_ADDRESS
              value: http://minids-api:8301
            - name: AUTH_JWK_URI
              value: http://auth-svc:8081/oauth2/jwks-rs256
            - name: AUTH_ISSUER_URI
              value: http://auth-svc:8081
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: minipay
spec:
  selector:
    app: user-svc
  ports:
    - name: http
      port: 8082
      targetPort: 8082
    - name: grpc
      port: 9082
      targetPort: 9082
