server:
  port: ${API_PORT:8301}

grpc:
  server:
    port: ${GRPC_PORT:9081}

spring:
  application:
    name: minids
  threads:
    virtual:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

minids:
  node-id:    ${NODE_ID:minids-0}
  raft-port:  ${RAFT_PORT:8300}
  raft-peers: ${RAFT_PEERS:minids-0:8301}
  data-dir:   ${DATA_DIR:./data/rocksdb}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    "[ro.minipay.minids]": DEBUG
    "[io.microraft]": INFO
